# Generated by Django 4.2.7 on 2023-11-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2023-11-30')),
                ('due_date', models.DateField(default='2023-11-30')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='app.category')),
            ],
        ),
    ]
