# Generated by Django 4.2.2 on 2023-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todolist_active_alter_todolist_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
